### ISSUE TITLE
Create .pcf(u) version of font.

### ISSUE THREAD

**Issue by DmitryHetman** [ntwk/atarist-font#1]

**Comment by ntwk** [comment]
I am assuming ".pcf(u)" is a typo and you actually are referring to PSF Linux console fonts.  There exist some tools which can help you convert BDF fonts to PSF fonts.

Check out:

- [gbdfed](http://sofia.nmsu.edu/~mleisher/Software/gbdfed/): A bitmap font editor which can edit BDF files and export them as PSF fonts
- [bdf2psf](https://packages.debian.org/sid/utils/bdf2psf): A Perl script which can convert BDF fonts to PSF fonts.  I've found this tool to be harder to use than gbdfed, but it is suitable for use in a Makefile.

The discussion in lucy/tewi-font#7 may also be of help here.
