### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by alexmyczko** [ntwk/atarist-font#5]
what is the license for the font?

**Comment by ntwk** [comment]
There's no license.

**Comment by alexmyczko** [comment]
![image](https://github.com/ntwk/atarist-font/assets/21078693/af72f3c0-3e1b-4d5d-adb6-6679aec9922a)

but stops us from adding it to Debian.

**Comment by ntwk** [comment]
@alexmyczko 🤣

I have added a BSD style license.

**Comment by alexmyczko** [comment]
Thank you!
